source: .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
gems:        []
timezone:    Asia/Seoul
encoding:    utf-8

future:      true
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     date
paginate_path: 'page:num'

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        8080 
baseurl:     /
url:         http://localhost:8080
lsi:         false

maruku:
 use_tex:    false
 use_divs:   false
 png_engine: blahtex
 png_dir:    images/latex
 png_url:    /images/latex

rdiscount:
 extensions: []

redcarpet:
 extensions: ['no_intra_emphasis', 'autolink']

kramdown:
 auto_ids: true
 footnote_nr: 1
 entity_output: as_char
 toc_levels: 1..6
 smart_quotes: lsquo,rsquo,ldquo,rdquo
 use_coderay: false

coderay:
 coderay_wrap: div
 coderay_line_numbers: inline
 coderay_line_numbers_start: 1
 coderay_tab_width: 4
 coderay_bold_every: 10
 coderay_css: style

redcloth:
 hard_breaks: true

category-list : [css,javascript,next,web,dev_story]
